add echo bot
dura0ok/Concerts-Suggester pull request #21
Opened 2024-02-29 08:13 UTC by Wooshey1411

2024-02-29 13:33 UTC, dura0ok requested changes
Сделал ревью

2024-02-29 13:33 UTC, dura0ok commented on telegramBot/src/main.py
> +async def start(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
Где отступ нормальный по PEP8?
Брат, скачай pycharm, там всё за тебя

2024-02-29 13:33 UTC, dura0ok commented on .gitignore
> +.env
добавь pycache, idea в gitignore

2024-02-29 13:33 UTC, dura0ok commented on telegramBot/src/main.py
> +async def help_command(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
вынеси команды в отдельный пакет

2024-02-29 13:33 UTC, dura0ok commented on telegramBot/src/requirements.txt
Надо использовать Poetry

2024-02-29 16:25 UTC, llirik42 commented on telegramBot/src/main.py
> +async def start(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
Кстати да, PyCharm же ругается если что-то не по PEP8. Как такое вообще могло произойти ...

2024-02-29 16:26 UTC, llirik42 commented on telegramBot/src/requirements.txt
Это Стёпа так шутит. Poetry -- менеджер пакетов (замена `pip`), который просто позволяет просматривать не просто список установленных пакетов, но и все зависимости: какой пакет от какой версии какого пакета зависит. Это удобно, но не супер принципиально

2024-03-01 16:28 UTC, dura0ok commented on telegramBot/handlers/bot_handlers.py
> +__all__ = ['start', 'help_command', 'echo']
Не нравится здесь мануальное вбитие всех функций ручками

2024-03-01 16:33 UTC, llirik42 commented on telegramBot/handlers/bot_handlers.py
> +__all__ = ['start', 'help_command', 'echo']
Любую из функций можно будет использовать и если она не указана в __all__

2024-03-01 16:46 UTC, dura0ok approved these changes

2024-03-01 16:57 UTC, dura0ok approved these changes

2024-03-01 16:59 UTC, merged